import { useOfficialDocuments, useDownloadOfficialDocument } from '@/features/requests/hooks/use-official-documents'
import { formatFileSize } from '@/shared/utils/file'
import { api } from '@/shared/api'
import { Button } from '@/shared/components/ui/button'
import { Skeleton } from '@/shared/components/ui/skeleton'
import { Badge } from '@/shared/components/ui/badge'
import { cn } from '@/shared/lib/utils'
import {
  FileBadge,
  Download,
  Eye,
  Calendar,
  User,
  AlertCircle,
} from 'lucide-react'

const DOCUMENT_TYPE_LABELS: Record<string, string> = {
  CERTIFICATE: 'Certificado',
  CONSTANCY: 'Constancia',
}

const DOCUMENT_TYPE_COLORS: Record<string, string> = {
  CERTIFICATE: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200',
  CONSTANCY: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200',
}

interface OfficialDocumentsSectionProps {
  requestId: string
}

export function OfficialDocumentsSection({ requestId }: OfficialDocumentsSectionProps) {
  const { data, isLoading, error } = useOfficialDocuments(requestId)
  const { download } = useDownloadOfficialDocument()

  const handleDownload = async (documentId: string, fileName: string) => {
    try {
      await download(requestId, documentId, fileName)
    } catch {
      // Error handled silently — could add toast notification
    }
  }

  const handleView = async (documentId: string) => {
    try {
      const response = await api.get(
        `/api/requests/${requestId}/official-documents/${documentId}/download`,
        { responseType: 'blob' }
      )
      const blob = new Blob([response.data], { type: 'application/pdf' })
      const url = window.URL.createObjectURL(blob)
      window.open(url, '_blank')
    } catch {
      // Error handled silently — could add toast notification
    }
  }

  if (isLoading) {
    return (
      <div className="rounded-2xl border border-border bg-surface">
        <div className="p-4 sm:p-6 border-b border-border">
          <div className="flex items-center gap-2">
            <FileBadge className="h-4 w-4 text-muted-foreground" />
            <h3 className="text-sm font-medium text-foreground">Documentos Oficiales</h3>
          </div>
        </div>
        <div className="p-4 sm:p-6">
          <div className="space-y-2.5">
            {Array.from({ length: 2 }).map((_, i) => (
              <Skeleton key={i} className="h-20 w-full rounded-lg" />
            ))}
          </div>
        </div>
      </div>
    )
  }

  if (error) {
    return null
  }

  const documents = data?.data ?? []
  const hasDocuments = documents.length > 0

  if (!hasDocuments) {
    return null
  }

  return (
    <div className="rounded-2xl border border-border bg-surface">
      <div className="p-4 sm:p-6 border-b border-border">
        <div className="flex items-center gap-2">
          <FileBadge className="h-4 w-4 text-muted-foreground" />
          <h3 className="text-sm font-medium text-foreground">Documentos Oficiales</h3>
          {documents.length > 0 && (
            <span className="text-xs text-muted-foreground">({documents.length})</span>
          )}
        </div>
      </div>

      <div className="p-4 sm:p-6">
        <div className="space-y-2.5 sm:space-y-3">
          {documents.map((doc) => {
            const typeLabel = DOCUMENT_TYPE_LABELS[doc.type] || doc.type
            const typeColor = DOCUMENT_TYPE_COLORS[doc.type] || 'bg-muted text-muted-foreground'
            const isAutoGenerated = doc.notes?.toLowerCase().includes('automáticamente') || doc.version === 1

            return (
              <div
                key={doc.id}
                className="group rounded-lg border border-border bg-surface p-3 sm:p-4 transition-all hover:border-primary/20 hover:shadow-sm"
              >
                <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3">
                  <div className="flex items-start gap-3 min-w-0 flex-1">
                    <div className="shrink-0 flex h-10 w-10 items-center justify-center rounded-lg bg-primary/5">
                      <FileBadge className="h-5 w-5 text-primary" />
                    </div>

                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2 flex-wrap mb-1">
                        <p className="text-sm font-semibold text-foreground">
                          {typeLabel}
                        </p>
                        <Badge variant="secondary" className={`text-eyebrow font-bold ${typeColor}`}>
                          v{doc.version}
                        </Badge>
                        <Badge
                          variant="outline"
                          className={cn(
                            "text-eyebrow font-semibold",
                            isAutoGenerated
                              ? "bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/50 dark:text-emerald-400 dark:border-emerald-800"
                              : "bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-950/50 dark:text-blue-400 dark:border-blue-800"
                          )}
                        >
                          {isAutoGenerated ? 'Auto' : 'Manual'}
                        </Badge>
                      </div>

                      <div className="flex items-center gap-2 sm:gap-3 text-xs text-muted-foreground mt-2 flex-wrap">
                        <span className="flex items-center gap-1">
                          <Calendar className="h-3 w-3" />
                          {formatDate(doc.createdAt)}
                        </span>
                        <span className="hidden sm:inline">{formatFileSize(doc.fileSize)}</span>
                        <span className="flex items-center gap-1 truncate">
                          <User className="h-3 w-3 shrink-0" />
                          <span className="truncate">{doc.generator?.fullName || '—'}</span>
                        </span>
                      </div>

                      {doc.notes && (
                        <p className="text-xs text-muted-foreground mt-2 italic line-clamp-2">
                          {doc.notes}
                        </p>
                      )}
                    </div>
                  </div>

                  <div className="flex items-center gap-1.5 shrink-0 sm:opacity-0 sm:group-hover:opacity-100 transition-opacity">
                    <Button
                      variant="outline"
                      size="sm"
                      className="h-9 sm:h-8 gap-1.5 flex-1 sm:flex-none px-3 sm:px-2.5"
                      onClick={() => handleView(doc.id)}
                      title="Ver PDF"
                    >
                      <Eye className="h-3.5 w-3.5" />
                      <span className="text-xs">Ver</span>
                    </Button>
                    <Button
                      variant="default"
                      size="sm"
                      className="h-9 sm:h-8 gap-1.5 flex-1 sm:flex-none px-3 sm:px-2.5"
                      onClick={() => handleDownload(doc.id, doc.fileName)}
                      title="Descargar PDF"
                    >
                      <Download className="h-3.5 w-3.5" />
                      <span className="text-xs">Descargar</span>
                    </Button>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {error && (
        <div className="px-4 sm:px-6 pb-4">
          <div className="flex items-start gap-2 rounded-lg border border-danger/20 bg-danger-soft px-3 py-2.5 text-sm text-danger">
            <AlertCircle className="h-4 w-4 mt-0.5 shrink-0" />
            <span>Error al cargar los documentos oficiales</span>
          </div>
        </div>
      )}
    </div>
  )
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('es-CO', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}
